AVX-17102: Use marketplace image to create controller and remove image variable
AviatrixSystems/terraform-module-gcp pull request #7
Opened 2021-11-23 18:54 UTC by mlin-aviatrix

2021-11-24 21:35 UTC, zhiqiangjin requested changes

2021-11-24 21:35 UTC, zhiqiangjin commented on aviatrix-controller-build/README.md
>    The CIDR for the Google Subnetwork that will be created. Must be empty if **network** is set. Default value is "10.128.0.0/9".
No indent. Please keep the format consistent with other modules.

2021-11-24 21:35 UTC, zhiqiangjin commented on aviatrix-controller-build/README.md
> -  The name or self_link of an existing Google compute image with the Aviatrix Controller Image. If not set, a Google Compute Image with the Aviatrix Controller image will be created.
Same here.

2021-11-24 21:35 UTC, zhiqiangjin commented on aviatrix-controller-build/README.md
>    Existing public IP Address to assign to the Aviatrix Controller. If not set, a Google Compute public IP address will be created.
Same.

2021-11-30 19:18 UTC, shuoliugit approved these changes

2021-11-30 19:19 UTC, mlin-aviatrix commented on aviatrix-controller-build/README.md
>    The CIDR for the Google Subnetwork that will be created. Must be empty if **network** is set. Default value is "10.128.0.0/9".
I was using the same format as the [AWS module](https://github.com/AviatrixSystems/terraform-modules/blob/master/aviatrix-controller-build/README.md), which has an indent there to so the text is that same indent as the bullet mark.

2021-12-07 19:03 UTC, merged